language: python
python:
- "2.7"
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
before_install:
    - sudo apt-get autoremove sqlite3
    - sudo apt-get install python-software-properties
    - sudo apt-add-repository -y ppa:travis-ci/sqlite3
    - sudo apt-get -y update
    - sudo apt-cache show sqlite3
    - sudo apt-get install sqlite3=3.7.15.1-1~travis1
    - sqlite3 --version
install:
    - pip install coverage coveralls flake8
script:
    - nosetests -sv --with-id --with-coverage --cover-package=simpletag --cover-branches --with-doctest
    - nosetests -sv --with-id --with-coverage --cover-package=simpletag --cover-branches --with-doctest
    - flake8 simpletag.py
after_success: coveralls
